from typing import Optional, List
from pydantic import BaseModel


class Member(BaseModel):
    member_id: Optional[int]
    # household_id: Optional[int]
    identification_date: Optional[str]
    order_number: Optional[int]
    structure: Optional[int]
    platform: Optional[int]
    social_center_code: Optional[str]
    household_old_code: Optional[str]
    household_code: Optional[str]
    member_code: Optional[str]
    dreams_code: Optional[str]
    dreams_date: Optional[str]
    # region: Optional[int]
    # department: Optional[int]
    # sub_prefecture: Optional[int]
    # village: Optional[int]
    # neighborhood: Optional[int]
    household_identification_id: Optional[int]
    last_name: Optional[str]
    first_name: Optional[str]
    gender: Optional[int]
    birthdate_month: Optional[int]
    birthdate_year: Optional[int]
    handicap: Optional[str]
    relation_with_chief: Optional[str]
    birthdate_certificate: Optional[str]
    birthdate_certificate_number: Optional[str]
    school_level: Optional[str]
    vulnerability: Optional[str]
    vulnerability_type: Optional[str]
    other_vulnerability_type: Optional[str]
    hiv_status: Optional[str]
    person_informed: Optional[str]
    other_person: Optional[str]
    arv_treatment_followup: Optional[str]
    care_giver_code: Optional[int]
    profession: Optional[str]
    needs: Optional[str]
    relation_with_adults: Optional[str]
    relation_with_children: Optional[str]
    relation_with_care_giver: Optional[str]
    becoming: Optional[str]
    other_becoming: Optional[str]
    registration_status: Optional[int]
    registration_status_changed: Optional[int]
    registration_status_report: Optional[int]
    registration_status_remove: Optional[int]

    class Config:
        orm_mode = True


class Household(BaseModel):
    identification_id: Optional[int]
    structure: Optional[int]
    platform: Optional[int]
    social_center_code: Optional[str]
    agent: Optional[str]
    identification_date_day: Optional[str]
    identification_date_month: Optional[str]
    identification_date_year: Optional[str]
    region: Optional[int]
    department: Optional[int]
    sub_prefecture: Optional[int]
    village: Optional[int]
    neighborhood: Optional[int]
    household_id: Optional[int]
    household_code: Optional[str]
    household_old_code: Optional[str]
    block: Optional[str]
    batch: Optional[str]
    reference: Optional[str]
    marital_status: Optional[str]
    wife_number: Optional[str]
    household_chief_handicap: Optional[str]
    member_number: Optional[str]
    entry_point: Optional[str]
    other_entry_point: Optional[str]
    active_persons_number: Optional[str]
    ovc_number: Optional[str]
    meal_number: Optional[str]
    housing_type: Optional[str]
    other_housing_type: Optional[str]
    room_number: Optional[str]
    house_situation: Optional[str]
    commodity: Optional[str]
    main_water_source: Optional[str]
    other_main_water_source: Optional[str]
    main_electricity_source: Optional[str]
    other_main_electricity_source: Optional[str]
    main_combustible: Optional[str]
    other_main_combustible: Optional[str]
    religion: Optional[str]
    other_religion: Optional[str]
    ethnicity: Optional[str]
    other_household_resource: Optional[str]
    social_capital: Optional[str]
    other_social_capital: Optional[str]
    main_incoming_source: Optional[str]
    other_incoming_source: Optional[str]
    estimated_monthly_expense: Optional[str]
    estimated_monthly_income: Optional[str]
    classification: Optional[str]
    graduation_status: Optional[int]
    registration_status: Optional[int]
    registration_status_change: Optional[int]
    registration_status_report: Optional[int]
    registration_status_remove: Optional[int]
    # members: List[Member]

    class Config:
        orm_mode = True
